create table messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  role text,
  content text,
  created_at timestamp default now()
);

alter table messages enable row level security;

create policy "Users can see their messages"
on messages for select
using (auth.uid() = user_id);

create policy "Users can insert their messages"
on messages for insert
with check (auth.uid() = user_id);